### PR TITLE
Adds pf1 system distance measurement as default if it exists and converts @ values to computed values in child auras

### LINKED ISSUE #10: Request:  use `pf1.utils.measureDistance` for distance calculations if available.
The distance calculation currently used doesnt seem to make it so a single nudge value compensates for weirdness. In my testing these are the nudge values needed at each 5 ft increment:
| distance| nudge value|
|--------|--------------|
|5 |3 |
|10 | 2|
|15 |1 |
|20 |1 |
|25 |1 |
|30 |1 |
| 35|1 |
| 40| breaks down |

Specifically, theres no way for a single nudge value to correctly grab every square it should.

The `pf1.utils.measureDistance` correctly measures distance between 2 characters and would fix the problem I think

### LINKED ISSUE #11: Request: Convert calculated values into their results on child buffs.
Not sure if this is even possible, but as is, you cant use variables in your buff changes since the buff is just a clone and the child tokens dont necessarily have the same hd/class levels/etc to give them the correct buff values.

### PR DESCRIPTION
**Pull request by bhudnell**
- Aura distance measurement now uses the `pf1.utils.measureDistance` function if it exists. If not, it falls back to the core foundry distance measurement
- Any `@` variables in changes are converted to their calculated values for child auras

closes https://github.com/FionaBrightgrass/Aura-Share/issues/10
closes https://github.com/FionaBrightgrass/Aura-Share/issues/11

### CODE REVIEW

**Comment by bhudnell** [comment]
@FionaBrightgrass Here's a PR to address both my feature requests

**Comment by bhudnell** [comment]
Thinking more about it, maybe these features should be settings that default to the old behavior so there arent any unexpected changes for people?

**Comment by bhudnell** [comment]
@FionaBrightgrass I saw you recently updated to use pf1 distance calculation. Any thoughts on my change to convert parent aura's `@` references before copying the aura to the child?

**Comment by FionaBrightgrass** [comment]
Hey Bhudnell. I added the line manually because I had made some major changes and we have some conflicts and it was easier to just do that. I hope you don't mind as it looks like it's just 1 line. Sorry about that!

**Comment by bhudnell** [comment]
No problem! Just happy it got merged in! Thanks for doing that 😄

**Pull request closed without merging**
